### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by ChuhuaW** [sanketsans/ganov2#2]
Hi,

Thanks for sharing your work. When I tried to load your [provided checkpoint ](https://drive.google.com/file/d/1UomhYn3SKnWfoNgH5jjngJ3aywc-kP-c/view) run inference on the v2 validation set, I encountered the following error: `RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`. 

Could you please take a look into this issue? Thank you.

**Comment by sanketsans** [comment]
Hi,
You can find the updated model [here](https://huggingface.co/sanketsans/ganov2/resolve/main/best.ckpt?download=true)
